import { Albert_Sans } from "next/font/google";
import "./globals.css";
import "./general-sans.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Navbar from "@/components/navbar/Navbar";

const albert_Sans = Albert_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={albert_Sans.className}>
        <Sidebar />
        <Navbar />
        <div className="pt-[120px] ml-[300px] min-h-[100vh] p-6 pb-10 bg-gray-100">
          {children}
        </div>
      </body>
    </html>
  );
}
